# Summary:
# Test actual example used in README.md
# Makes sure the GitHub Action builds when being built by GitHub Actions.
#
# See https://github.com/actions/checkout https://github.com/actions/checkout/releases/tag/v2

name: 'GitHub Action code snippet'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  compute-data:
    name: Compute data
    runs-on: ubuntu-18.04
    steps:
      - name: Compute ressource
        run: |
          MAGIC_NUMBER=42
          echo "Found universal answer: $MAGIC_NUMBER"
          echo "Exporting it..."
          echo "MAGIC_NUMBER=$MAGIC_NUMBER" >> $GITHUB_ENV

      - name: Export variable for next jobs
        uses: UnlyEd/github-action-store-variable@v2.0.0 # See https://github.com/UnlyEd/github-action-store-variable
        with:
          variables: |
            MAGIC_NUMBER=${{ env.MAGIC_NUMBER }}

  retrieve-data:
    name: Find & re-use data
    runs-on: ubuntu-18.04
    needs: compute-data
    steps:
      - name: Import variable MAGIC_NUMBER
        uses: UnlyEd/github-action-store-variable@v2.0.0 # See https://github.com/UnlyEd/github-action-store-variable
        with:
          variables: MAGIC_NUMBER
          failIfNotFound: true
      - name: Debug output
        run: echo "We have access to $MAGIC_NUMBER"

  save-many-variables-by-using-custom-delimiter:
    name: Save many variable by using a custom delimiter (comma)
    runs-on: ubuntu-18.04
    steps:
      - name: Export variable for next jobs
        uses: UnlyEd/github-action-store-variable@v2.0.0 # See https://github.com/UnlyEd/github-action-store-variable
        with:
          delimiter: ','
          variables: FOO=BAR,STAGE=production

  retrieve-data-saved-with-a-custom-delimiter:
    name: Retrieve data saved with a custom delimiter
    runs-on: ubuntu-18.04
    needs: save-many-variables-by-using-custom-delimiter
    steps:
      - name: Import variable MAGIC_NUMBER
        uses: UnlyEd/github-action-store-variable@v2.0.0 # See https://github.com/UnlyEd/github-action-store-variable
        with:
          delimiter: ';'
          variables: FOO;STAGE
          failIfNotFound: true
      - name: Debug output
        run: echo "Found FOO=$FOO and STAGE=$STAGE"